### ISSUE TITLE
background表插入报错

### ISSUE THREAD

**Issue by northeastsquare** [510team/wechat-app-server#2]
你好，创建数据库sql语句中，报错了，谢谢：
INSERT INTO `background` VALUES ('1', '/static/background1@2x.png', '1'), ('2', '/static/background2@2x.png', '0'), ('3', '/static/background3@2x.png', '0'), ('4', '/static/background4@2x.png', '0');

**Comment by scofieldfan** [comment]
报什么错呢？这个是一个换背景图的功能。去掉这个应该也可以运行

**Comment by northeastsquare** [comment]
后来弄好了
